---
title: "Illustration"
author: "Wenhao Gou | wg2364"
date: "4/17/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(extraDistr)
library(dplyr)
library(MASS)
library(LaplacesDemon)
```


```{r,eval=F}
data = read.csv("hurrican356.csv")
df = data %>%
  mutate(Month = factor(Month, levels = c("January", "April", "May", "June", "July", "August",
                                           "September", "October", "November", "December")),
         Month = as.numeric(Month),
         Nature = as.numeric(as.factor(Nature)))
id = df %>% group_by(Season, ID) %>% summarize(n = n())

upd.bi = function(df, epis, beta, sigma, n){
  sd = solve(epis + diag(n*sigma, 8, 8)) # posterior distribution for beta.i 
  mu = sd %*% (epis %*% beta + sigma*sum(df %*% beta)) # posterior distribution for beta.i
  return(list(sd = sd, mu = mu))}
mc = function(df, a, b, ini.sigma, niter = 2){

  d.lat = sapply(2:nrow(df), function(i){df[i,7] - df[i-1, 7]})
  d.lon = sapply(2:nrow(df), function(i){df[i,8] - df[i-1, 8]})
  d.spd = sapply(2:nrow(df), function(i){df[i,9] - df[i-1, 9]})
  d.yi = df[-1,9]
  dt = cbind(d.yi, df[-1,1], df[-1,4], df[-1,3], df[-1,5], df[-nrow(df),9], d.lat, d.lon, d.spd) 
  # final dataset for each individual grp

  delta1 = c(0, sapply(2:nrow(df), function(i){df[i,7] - df[i-1, 7]}))
  delta2 = c(0, sapply(2:nrow(df), function(i){df[i,8] - df[i-1, 8]}))
  delta3 = c(0, sapply(2:nrow(df), function(i){df[i,9] - df[i-1, 9]}))
  dt = cbind(df[,1], df[,4], df[,3], df[,5], df[,9], delta1, delta2, delta3) # final dataset for each individual group

  n = nrow(dt)
  epis = vector("list", niter)
  beta = matrix(NA, nrow = 8, ncol = niter)
  beta.i = matrix(NA, nrow = 8, ncol = niter)
  sigma = rep(NA, niter)
  epis[[1]] = cor(matrix(1/extraDistr::rinvgamma(64, alpha = a, beta = b), 8, 8)) 
  # initial epsilon^-1 ~ inverse.gamma(0.001, 0.001) (8x8)
  beta[,1] = rep(1, 8) # initial beta (8x1)
  sigma[1] = ini.sigma # initial sigma 
  beta.i[,1] = mvrnorm(1, mu = upd.bi(dt, epis[[1]], beta[,1], sigma[1], n)$mu, 
  Sigma = upd.bi(dt, epis[[1]], beta[,1], sigma[1], n)$sd) 
  # mvrnorm generates the beta_i for each subgroup(8x1) - beta.i ~ N(beta, epsilon)
  for (i in 2:niter){
    epis[[i]] = rinvwishart(n + a, diag(sum((beta.i[,i-1] - beta[,i-1])^2), 8, 8) + 0.001) 
    # use beta.i and beta update epsilon, pi(epsilon) ~ Inviwishart(n + a, beta_variance + b)!!!!!!!!(May change back to inverse gamma?????)
    beta[,i] = mvrnorm(1, mu = n*beta.i[,i-1], Sigma = n*epis[[i]])  # beta ~ N(n*beta_i, n*epsilon)
    sigma[i] = extraDistr::rinvgamma(1, alpha = n + 1, sum((dt[,5] - dt %*% beta.i[,i-1])^2)) 
    # sigma ~ inverse.gamma(n + 1, sample residual of Yi)
    beta.i[,i] = mvrnorm(1, mu = upd.bi(dt, epis[[i]], beta[,i], sigma[i], n)$mu, 
  Sigma = upd.bi(dt, epis[[i]], beta[,i], sigma[i], n)$sd)}
  return(list(beta.i =  beta.i))}

grp = function(df, id){
  sub.grp = vector("list", nrow(id))
  id.n = c(0, id$n)
  for (i in 1:length(sub.grp)){
    sub.grp[[i]] = df[(id.n[i]+1):id.n[i+1],]}
  return(sub.grp)}
 
```

Posterior Distribution Inference: see formula.pdf for detail.


# Reference:

1. https://downloads.hindawi.com/journals/jps/2014/673657.pdf

2. http://www.stat.cmu.edu/~brian/463-663/week10/Chapter%2009.pdf

